### ISSUE TITLE
Error while performing build

### ISSUE THREAD

**Issue by PhilPalmer** [singularityhub/singularity2docker#10]
Hi,

Thanks for a great tool!

I am trying to convert four Singularity images into Docker images. I have managed to convert 3/4 images however I am having issues with one of them.

If I try running the following:
```
./singularity2docker.sh -n lifebitai/leafcutter:latest leafcutter.img
```

I get this error:
```
Input Image: leafcutter.img
Cleanup: true

1. Checking for software dependencies, Singularity and Docker...
Found singularity singularity version 3.3.0
Found docker Docker version 18.09.7, build 2d0083d
Found jq jq-1.5-1-a5b5cbe

2.  Preparing sandbox for export...
INFO:    Starting build...
ERROR:   unpackSquashfs Failed: Trimming header Failed: exit status 1: dd: invalid number: ‘0’
FATAL:   While performing build: packer failed to pack: Trimming header Failed: exit status 1: dd: invalid number: ‘0’
```

I think the issue occurs when running [this line](https://github.com/singularityhub/singularity2docker/blob/master/singularity2docker.sh#L134):
```bash
singularity build --sandbox ${sandbox} ${image}
```

Any idea what might be causing the issue?

Any help would be much appreciated, thanks in advance

**Comment by vsoch** [comment]
Can you confirm reproducing the issue with that exact build command with the sandbox, e.g.

```bash
singularity build --sandbox /tmp/sandbox.box container.sif
```
If that is indeed the error, you should report this on the Sylabs board at https://github.com/sylabs/singularity/issues. This script just serves as a wrapper to that. If it worked for other images, my guess would be that this particular container was built with a different version, or perhaps it's larger and there is some error with filesystem space or memory. I don't know enough about the unpacking to guess more than that. 

Please let me know if you figure it out, and please reference the issue so that I'm updated when there is discussion / change.

**Comment by PhilPalmer** [comment]
Hi @vsoch,

Thanks for the quick reply.

I tested with this command and that does seem to indeed be the issue.  In the end, I just used a different container. I'll close this now as the issue isn't to do with your script.

Thanks again
